### ISSUE TITLE
Running etl.py multiple times causes db errors

### ISSUE THREAD

**Issue by eads** [Illinois-Campaign-for-Political-Reform/illinois-sunshine#157]
```bash
$ python etl.py --download --load_data --recreate_views

download start 2017-07-18T16:56:10.549865 ...
download finish 2017-07-18T16:57:14.093512 ...
loading data start 2017-07-18T16:57:14.093539 ...
(psycopg2.ProgrammingError) type "committee_position" already exists
 [SQL: "\n            CREATE TYPE committee_position AS ENUM (\n              'support',\n              'oppose'\n            )\n        "]
Traceback (most recent call last):
  File "/Users/DE-Admin/.virtualenvs/illinois-sunshine/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/Users/DE-Admin/.virtualenvs/illinois-sunshine/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: type "committee_position" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "etl.py", line 60, in executeTransaction
    self.connection.execute(query, *args)
  File "/Users/DE-Admin/.virtualenvs/illinois-sunshine/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 906, in execute
    return self._execute_text(object, multiparams, params)
  File "/Users/DE-Admin/.virtualenvs/illinois-sunshine/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1054, in _execute_text
    statement, parameters
  File "/Users/DE-Admin/.virtualenvs/illinois-sunshine/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/Users/DE-Admin/.virtualenvs/illinois-sunshine/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/Users/DE-Admin/.virtualenvs/illinois-sunshine/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/Users/DE-Admin/.virtualenvs/illinois-sunshine/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 181, in reraise
    raise value.with_traceback(tb)
  File "/Users/DE-Admin/.virtualenvs/illinois-sunshine/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/Users/DE-Admin/.virtualenvs/illinois-sunshine/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) type "committee_position" already exists
 [SQL: "\n            CREATE TYPE committee_position AS ENUM (\n              'support',\n              'oppose'\n            )\n        "]
(psycopg2.ProgrammingError) type "committee_position" already exists
 [SQL: "\n            CREATE TYPE committee_position AS ENUM (\n              'support',\n              'oppose'\n            )\n        "]
^CTraceback (most recent call last):
  File "etl.py", line 2118, in <module>
    main(parser.parse_args())
  File "etl.py", line 2006, in main
    officers.load(update_existing=True)
  File "etl.py", line 285, in load
    self.bulkLoadRawData()
  File "etl.py", line 226, in bulkLoadRawData
    curs.copy_expert(copy_st, f)
KeyboardInterrupt
```

**Comment by eads** [comment]
It appears to simply print the error and then proceed via an overly broad try/except. I suspect there's a better way.

**Comment by eads** [comment]
Was this merged?
